Traceback (most recent call last):
  File "/g/data/xf3/zz3507/envs/HiC-Pro/HiC-Pro_3.1.0/bin/utils/digest_genome.py", line 186, in <module>
    with open(out, 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: './HiCProDigestGenome/DigestEnzymeH1HiCPro.bed'
